### ISSUE TITLE
Is it possible to update skills incrementally?

### ISSUE THREAD

**Issue by apiss2** [glandfried/TrueSkillThroughTime.py#8]
Hello,
Thank you for the amazing tool!

I find this tool very useful for quantifying players' skills using post-event information.

Therefore, in cases where matches are held weekly, I think it would be convenient to have a way to incrementally add match results. Is there a way to do this?

Also, if such a method is currently unavailable, are there any plans to add it in the future?

**Comment by glandfried** [comment]
Sorry for the delay in replying. The day I received the message I saw your repository https://github.com/apiss2/ttt_cpp. I fork it, but I couldn't review it yet. I the long term it would be great if we replace all implementations by one single version in C++. Regarding your question, at the moment there is no method for adding new events incrementally. But it is not really difficult to do it. Your C++ version works well? If so, you will know how to do it. Maybe we must open a Discord channel to discuss with you and others that were interested in the last years. Maybe we can also work on your C++ version. If you want, I think we can add a link to you repo from the main project: https://github.com/glandfried/TrueSkillThroughTime. There is a big community that wants this and others features. If we open the Discord and I add a link to your repo, I think the method will be implemented sooner rather than later.

**Comment by apiss2** [comment]
Thank you for your response.

1, Unfortunately, my C++ version currently does not have the capability to incrementally add events. However, I believe it would work by simply separating the trueskill functionality from the constructor in the History class.
2, Additionally, my C++ version is not yet fully operational.
3, However, if you open a repository for the C++ version, I would be happy to collaborate, so please let me know when you do.

Best regards.

**Comment by glandfried** [comment]
I will be upgrading all packages this year, including the option to add match incrementally, but I don't think I will be able to do it in the next 3 months. If anyone wants to make a pull request, welcome.

**Comment by apiss2** [comment]
I understand!

I have created a new pull request, please review it.

**Comment by glandfried** [comment]
[Version V2.0.0 is coming soon](https://github.com/glandfried/TrueSkillThroughTime.py/pull/13#issue-3627591607)
